'use strict';var p=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,e){if(a==Array.prototype||a==Object.prototype)return a;a[b]=e.value;return a};function r(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var e=a[b];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");}var t=r(this);
function u(a,b){if(b)a:{var e=t;a=a.split(".");for(var f=0;f<a.length-1;f++){var h=a[f];if(!(h in e))break a;e=e[h]}a=a[a.length-1];f=e[a];b=b(f);b!=f&&b!=null&&p(e,a,{configurable:!0,writable:!0,value:b})}}function v(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function w(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:v(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function x(){this.j=!1;this.h=null;this.o=void 0;this.g=1;this.u=this.l=0;this.i=null}function y(a){if(a.j)throw new TypeError("Generator is already running");a.j=!0}x.prototype.m=function(a){this.o=a};function z(a,b){a.i={I:b,isException:!0};a.g=a.l||a.u}
x.prototype.return=function(a){this.i={return:a};this.g=this.u};function A(a,b,e){a.g=e;return{value:b}}function B(a){this.g=new x;this.h=a}function F(a,b){y(a.g);var e=a.g.h;if(e)return G(a,"return"in e?e["return"]:function(f){return{value:f,done:!0}},b,a.g.return);a.g.return(b);return H(a)}
function G(a,b,e,f){try{var h=b.call(a.g.h,e);if(!(h instanceof Object))throw new TypeError("Iterator result "+h+" is not an object");if(!h.done)return a.g.j=!1,h;var k=h.value}catch(c){return a.g.h=null,z(a.g,c),H(a)}a.g.h=null;f.call(a.g,k);return H(a)}
function H(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.j=!1,{value:b.value,done:!1}}catch(e){a.g.o=void 0,z(a.g,e)}a.g.j=!1;if(a.g.i){b=a.g.i;a.g.i=null;if(b.isException)throw b.I;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function I(a){this.next=function(b){y(a.g);a.g.h?b=G(a,a.g.h.next,b,a.g.m):(a.g.m(b),b=H(a));return b};this.throw=function(b){y(a.g);a.g.h?b=G(a,a.g.h["throw"],b,a.g.m):(z(a.g,b),b=H(a));return b};this.return=function(b){return F(a,b)};this[Symbol.iterator]=function(){return this}}function J(a){function b(f){return a.next(f)}function e(f){return a.throw(f)}return new Promise(function(f,h){function k(c){c.done?f(c.value):Promise.resolve(c.value).then(b,e).then(k,h)}k(a.next())})}
u("Symbol",function(a){function b(k){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new e(f+(k||"")+"_"+h++,k)}function e(k,c){this.g=k;p(this,"description",{configurable:!0,writable:!0,value:c})}if(a)return a;e.prototype.toString=function(){return this.g};var f="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",h=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");p(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return K(v(this))}});return a});function K(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
u("Promise",function(a){function b(c){this.h=0;this.i=void 0;this.g=[];this.o=!1;var d=this.j();try{c(d.resolve,d.reject)}catch(g){d.reject(g)}}function e(){this.g=null}function f(c){return c instanceof b?c:new b(function(d){d(c)})}if(a)return a;e.prototype.h=function(c){if(this.g==null){this.g=[];var d=this;this.i(function(){d.l()})}this.g.push(c)};var h=t.setTimeout;e.prototype.i=function(c){h(c,0)};e.prototype.l=function(){for(;this.g&&this.g.length;){var c=this.g;this.g=[];for(var d=0;d<c.length;++d){var g=
c[d];c[d]=null;try{g()}catch(l){this.j(l)}}}this.g=null};e.prototype.j=function(c){this.i(function(){throw c;})};b.prototype.j=function(){function c(l){return function(m){g||(g=!0,l.call(d,m))}}var d=this,g=!1;return{resolve:c(this.C),reject:c(this.l)}};b.prototype.C=function(c){if(c===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof b)this.F(c);else{a:switch(typeof c){case "object":var d=c!=null;break a;case "function":d=!0;break a;default:d=!1}d?this.B(c):this.m(c)}};
b.prototype.B=function(c){var d=void 0;try{d=c.then}catch(g){this.l(g);return}typeof d=="function"?this.G(d,c):this.m(c)};b.prototype.l=function(c){this.u(2,c)};b.prototype.m=function(c){this.u(1,c)};b.prototype.u=function(c,d){if(this.h!=0)throw Error("Cannot settle("+c+", "+d+"): Promise already settled in state"+this.h);this.h=c;this.i=d;this.h===2&&this.D();this.J()};b.prototype.D=function(){var c=this;h(function(){if(c.A()){var d=t.console;typeof d!=="undefined"&&d.error(c.i)}},1)};b.prototype.A=
function(){if(this.o)return!1;var c=t.CustomEvent,d=t.Event,g=t.dispatchEvent;if(typeof g==="undefined")return!0;typeof c==="function"?c=new c("unhandledrejection",{cancelable:!0}):typeof d==="function"?c=new d("unhandledrejection",{cancelable:!0}):(c=t.document.createEvent("CustomEvent"),c.initCustomEvent("unhandledrejection",!1,!0,c));c.promise=this;c.reason=this.i;return g(c)};b.prototype.J=function(){if(this.g!=null){for(var c=0;c<this.g.length;++c)k.h(this.g[c]);this.g=null}};var k=new e;b.prototype.F=
function(c){var d=this.j();c.v(d.resolve,d.reject)};b.prototype.G=function(c,d){var g=this.j();try{c.call(d,g.resolve,g.reject)}catch(l){g.reject(l)}};b.prototype.then=function(c,d){function g(n,q){return typeof n=="function"?function(C){try{l(n(C))}catch(D){m(D)}}:q}var l,m,E=new b(function(n,q){l=n;m=q});this.v(g(c,l),g(d,m));return E};b.prototype.catch=function(c){return this.then(void 0,c)};b.prototype.v=function(c,d){function g(){switch(l.h){case 1:c(l.i);break;case 2:d(l.i);break;default:throw Error("Unexpected state: "+
l.h);}}var l=this;this.g==null?k.h(g):this.g.push(g);this.o=!0};b.resolve=f;b.reject=function(c){return new b(function(d,g){g(c)})};b.race=function(c){return new b(function(d,g){for(var l=w(c),m=l.next();!m.done;m=l.next())f(m.value).v(d,g)})};b.all=function(c){var d=w(c),g=d.next();return g.done?f([]):new b(function(l,m){function E(C){return function(D){n[C]=D;q--;q==0&&l(n)}}var n=[],q=0;do n.push(void 0),q++,f(g.value).v(E(n.length-1),m),g=d.next();while(!g.done)})};return b});
u("Array.from",function(a){return a?a:function(b,e,f){e=e!=null?e:function(d){return d};var h=[],k=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof k=="function"){b=k.call(b);for(var c=0;!(k=b.next()).done;)h.push(e.call(f,k.value,c++))}else for(k=b.length,c=0;c<k;c++)h.push(e.call(f,b[c],c));return h}});var L=null,M=!1,N=[];chrome.runtime.onMessage.addListener(function(a,b,e){a.target==="offscreen"&&a.type==="StartScreenRecording"&&(O(a.H),e({success:!0}))});
function O(a){J(new I(new B(function(b){if(b.g==1){if(M)return b.return();b.l=2;return A(b,navigator.mediaDevices.getDisplayMedia({video:{displaySurface:"monitor"}}).then(function(e){M=!0;try{N=[],L=new MediaRecorder(e,{mimeType:"video/webm;codecs=vp9"}),L.ondataavailable=function(f){f.data.size>0&&N.push(f.data)},L.onstop=function(){var f,h,k;return J(new I(new B(function(c){if(c.g==1)return f=new Blob(N,{type:"video/webm"}),A(c,f.arrayBuffer(),2);if(c.g!=3)return h=c.o,k=new Uint8Array(h),A(c,chrome.runtime.sendMessage({target:"background",
action:"SaveScreenRecording",K:Array.from(k),filename:"screen-recording-"+Date.now()+".webm",H:a}),3);M=!1;e.getTracks().forEach(function(d){return d.stop()});c.g=0})))},L.start()}catch(f){M=!1}}),4)}b.g!=2?(b.g=0,b.l=0):(b.l=0,b.i=null,b.g=0)})))};
